/*
 * Script de criação das tabelas para Oracle.
 * Você deve rodar isso dentro do seu Oracle SQL Developer.
 */

-- Tabela 1: Usuario
CREATE TABLE Usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    senha VARCHAR2(100) NOT NULL,
    is_admin NUMBER(1) DEFAULT 0 -- 0 para FALSE, 1 para TRUE
);

-- Tabela 2: RecursoAjuda
CREATE TABLE RecursoAjuda (
    id_recurso NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    descricao CLOB, -- CLOB é melhor para textos longos no Oracle
    link_externo VARCHAR2(500) NOT NULL,
    categoria VARCHAR2(50)
);

-- Tabela 3: RegistroBemEstar
CREATE TABLE RegistroBemEstar (
    id_registro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    data_registro DATE DEFAULT SYSDATE, -- SYSDATE é o CURRENT_TIMESTAMP do Oracle
    emocao_selecionada VARCHAR2(50) NOT NULL,
    comentario CLOB,
    
    CONSTRAINT fk_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES Usuario(id_usuario)
);

-- --- DADOS DE EXEMPLO ---

-- Criar um usuário Admin (is_admin = 1)
INSERT INTO Usuario (nome, email, senha, is_admin) 
VALUES ('Maria (Admin)', 'admin@zen.work', 'admin', 1);

-- Criar um usuário Funcionário (is_admin = 0)
INSERT INTO Usuario (nome, email, senha, is_admin) 
VALUES ('João Silva', 'joao@zen.work', '123', 0);

-- Adicionar alguns recursos de ajuda de exemplo
INSERT INTO RecursoAjuda (titulo, descricao, link_externo, categoria)
VALUES 
('Guia de Meditação de 5 Minutos', 'Uma prática rápida para acalmar a mente e focar no presente.', '#', 'Mindfulness');

INSERT INTO RecursoAjuda (titulo, descricao, link_externo, categoria)
VALUES 
('Técnicas de Respiração para Acalmar', 'Aprenda exercícios de respiração simples e eficazes.', '#', 'Ansiedade');

INSERT INTO RecursoAjuda (titulo, descricao, link_externo, categoria)
VALUES 
('Artigo: Como Lidar com o Estresse', 'Estratégias práticas para identificar e gerenciar o estresse.', '#', 'Artigo');

INSERT INTO RecursoAjuda (titulo, descricao, link_externo, categoria)
VALUES 
('Alongamentos para Aliviar a Tensão', 'Uma série de alongamentos para fazer na sua mesa.', '#', 'Exercício');

-- Confirma as inserções
COMMIT;